"""init

Revision ID: 1f81ff1f1e28
Revises: 
Create Date: 2025-05-18 19:24:19.323188

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f81ff1f1e28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_name'), 'collection', ['name'], unique=False)
    op.create_table('tag',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('link_entry',
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_entry_url'), 'link_entry', ['url'], unique=False)
    op.create_table('link_ai_suggestion',
    sa.Column('link_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['link_entry.id'], ),
    sa.PrimaryKeyConstraint('link_id')
    )
    op.create_table('taglinkassociation',
    sa.Column('tag_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('link_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['link_entry.id'], ),
    sa.ForeignKeyConstraint(['tag_name'], ['tag.name'], ),
    sa.PrimaryKeyConstraint('tag_name', 'link_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taglinkassociation')
    op.drop_table('link_ai_suggestion')
    op.drop_index(op.f('ix_link_entry_url'), table_name='link_entry')
    op.drop_table('link_entry')
    op.drop_table('tag')
    op.drop_index(op.f('ix_collection_name'), table_name='collection')
    op.drop_table('collection')
    # ### end Alembic commands ###
