"""Add scrapper job table

Revision ID: 3d1b3bfa60b6
Revises: 1f81ff1f1e28
Create Date: 2025-05-31 22:40:11.446689

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d1b3bfa60b6'
down_revision: Union[str, None] = '1f81ff1f1e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrapper_job',
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrapper_job_status'), 'scrapper_job', ['status'], unique=False)
    op.create_index(op.f('ix_scrapper_job_url'), 'scrapper_job', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scrapper_job_url'), table_name='scrapper_job')
    op.drop_index(op.f('ix_scrapper_job_status'), table_name='scrapper_job')
    op.drop_table('scrapper_job')
    # ### end Alembic commands ###
