"""cascade_tags

Revision ID: 6ed2c666bbbf
Revises: 743cf0af9772
Create Date: 2025-06-16 23:10:23.716422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '6ed2c666bbbf'
down_revision: Union[str, None] = '743cf0af9772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bookmark_ai_suggestion_collection_id_fkey', 'bookmark_ai_suggestion', type_='foreignkey')
    op.create_foreign_key(None, 'bookmark_ai_suggestion', 'collection', ['collection_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('tag_bookmark_association_tag_name_fkey', 'tag_bookmark_association', type_='foreignkey')
    op.drop_constraint('tag_bookmark_association_bookmark_id_fkey', 'tag_bookmark_association', type_='foreignkey')
    op.create_foreign_key(None, 'tag_bookmark_association', 'bookmark', ['bookmark_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tag_bookmark_association', 'tag', ['tag_name'], ['name'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag_bookmark_association', type_='foreignkey')
    op.drop_constraint(None, 'tag_bookmark_association', type_='foreignkey')
    op.create_foreign_key('tag_bookmark_association_bookmark_id_fkey', 'tag_bookmark_association', 'bookmark', ['bookmark_id'], ['id'])
    op.create_foreign_key('tag_bookmark_association_tag_name_fkey', 'tag_bookmark_association', 'tag', ['tag_name'], ['name'])
    op.drop_constraint(None, 'bookmark_ai_suggestion', type_='foreignkey')
    op.create_foreign_key('bookmark_ai_suggestion_collection_id_fkey', 'bookmark_ai_suggestion', 'collection', ['collection_id'], ['id'])
    # ### end Alembic commands ###
