"""cascade_relations

Revision ID: 743cf0af9772
Revises: c48a016c43c6
Create Date: 2025-06-16 23:07:17.319708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '743cf0af9772'
down_revision: Union[str, None] = 'c48a016c43c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bookmark_collection_id_fkey', 'bookmark', type_='foreignkey')
    op.create_foreign_key('bookmark_collection_id_fkey', 'bookmark', 'collection', ['collection_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('bookmark_ai_suggestion_bookmark_id_fkey', 'bookmark_ai_suggestion', type_='foreignkey')
    op.create_foreign_key('bookmark_ai_suggestion_bookmark_id_fkey', 'bookmark_ai_suggestion', 'bookmark', ['bookmark_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('job_bookmark_id_fkey', 'job', type_='foreignkey')
    op.create_foreign_key("job_bookmark_id_fkey", 'job', 'bookmark', ['bookmark_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('job_bookmark_id_fkey', 'job', type_='foreignkey')
    op.create_foreign_key('job_bookmark_id_fkey', 'job', 'bookmark', ['bookmark_id'], ['id'])
    op.drop_constraint('bookmark_ai_suggestion', 'bookmark_ai_suggestion', type_='foreignkey')
    op.create_foreign_key('bookmark_ai_suggestion_bookmark_id_fkey', 'bookmark_ai_suggestion', 'bookmark', ['bookmark_id'], ['id'])
    op.drop_constraint('bookmark_ai_suggestion_bookmark_id_fkey', 'bookmark', type_='foreignkey')
    op.create_foreign_key('bookmark_collection_id_fkey', 'bookmark', 'collection', ['collection_id'], ['id'])
    # ### end Alembic commands ###
