"""tags_field

Revision ID: 95518561bc41
Revises: 7c60d8eada85
Create Date: 2025-06-15 21:52:43.001305

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95518561bc41'
down_revision: Union[str, None] = '7c60d8eada85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark_ai_suggestion', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmark_ai_suggestion', 'tags')
    # ### end Alembic commands ###
