"""change-to-nullable

Revision ID: d80ff81ffa6f
Revises: ead5a63b90cd
Create Date: 2025-06-02 20:10:38.271600

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80ff81ffa6f'
down_revision: Union[str, None] = 'ead5a63b90cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookmark', 'collection_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookmark', 'collection_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
